server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://172.20.113.40:8761/eureka/