server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    statusPageUrlPath: ${server.servletPath}/info
    healthCheckUrlPath: ${server.servletPath}/health
  client:
    register-with-eureka: true
    fetch-registry: false
    #serviceUrl:
      #defaultZone: http://3.36.85.165:8761/eureka/