server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    #serviceUrl:
      #defaultZone: http://3.36.85.165:8761/eureka/

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    web:
      exposure:
        include: '*'
    metrics:
      enabled: true
