server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://a7f9443d24006441fa3d51c97e8a3acc-1892618396.ap-northeast-2.elb.amazonaws.com:8761/eureka/
